name: build-and-release

on:
  push:
    # not not consider simplec commit
    branches:
      - '!*'
    # consider only release and pre-release tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-ora'
      - 'v[0-9]+.[0-9]+.[0-9]+-ora[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ora-rc[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-ora[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: cache go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: tests
        run: |
          go test -v ./...

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: github-actions
